version: '3'
services:
  socket:
    build: .
    ports:
      - "8888:8888"
    environment:
      - CMD=socket
      - NODE_ENV=dev
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"
